{% set name = "gerrychain" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5eec69a8db53beaf5e2e9ede80876c44154aaf802c048bd4a3661405736b8a6b

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - geopandas
    - networkx
    - pandas
    - python >=3.6
    - shapely

test:
  imports:
    - gerrychain
    - gerrychain.constraints
    - gerrychain.graph
    - gerrychain.partition
    - gerrychain.proposals
    - gerrychain.updaters
    - gerrychain.metrics
    - gerrychain.vendor
    - gerrychain.vendor.utm

about:
  home: https://github.com/mggg/GerryChain
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Use Markov chain Monte Carlo to analyze districting plans and gerrymanders
  doc_url: https://gerrychain.readthedocs.io/
  dev_url: https://github.com/mggg/GerryChain

extra:
  recipe-maintainers:
    - bsuwal
