travis:
  secure:
    BINSTAR_TOKEN: GWZY0cT/P6IGM7K3wq3bnY65SIbvCnnPiz95Uh0Bvdi2V2bW3mUl4EprniSzJZx67e4+NUAO74iBy0xD+PwllpNf4YMRtwRD8I2c1761TV53E6CsumxQlg/tn3v0zf+xcFJl9+SVrbxs1/pjwEEZWfPYf7JfQFnngOJpm7RBShVP+5aqYYHCTG/q6zphlfhVTu/ibYeoo20/PvkSsuuDzTe/2A+Uty8GTpoGh55jGu8ceyk7mxgVl+vh3EYelCWB5x3LieQgOxQ7aEj/ZDpy0olbhs1tCf7BcybpqvLFgjUmYUiRfIVwsiVEbtjmOmB2nYZhm5von9NX/MLXpLXierSQUpvXolue+eop8HrW4rPAa9sq26D1oyqKfprwrLFnkNpPDNhycOa9+BHqhmaYjut/U0MOPtm3iXif9NqRpWEJpQR2Yhw8mIY7gMPnLzttR9B+5pU4432h5z25+JKK6VSIW3M2JL/kID2hOLBWe82R91D1tgKWSdsUK+8Df5kfo4v33CG8SPp7V+JaSO9UQ1l9p5ouEn18Lycr3Y1d/h4VFiYMoQQJaR6VYqXR4LId+W1okMayuXM6g6Lw1kqli6/4449eldXF6pmFBn2fdG25ITbCeuwLHrHRw62uPMBJQYX0flNA7nVZZA6LChgEQ9ig7d10GFLm+sTcZWjLdXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
